// ================================
// Plant MODEL - Matches PostgreSQL Tables EXACTLY
// ================================

export interface ILocation {
  location_type: string; // matches column: location_type
  location_value: string; // matches column: location_value
}

export interface IPlant {
  id?: string; // UUID (generated by PostgreSQL)

  scientific_name: string; // VARCHAR(255) NOT NULL
  common_name: string; // VARCHAR(255) NOT NULL

  image_search_url?: string | null; // TEXT

  description?: string | null; // TEXT
  native?: boolean | null; // BOOLEAN
  light?: string | null; // VARCHAR(100)
  water_needs?: string | null; // VARCHAR(100)
  maintenance_level?: string | null; // VARCHAR(100)
  growth_form?: string | null; // VARCHAR(100)
  // ================================
  // Linked 1-to-many relations
  // ================================
  space_types?: string[]; // from plant_space_types table
  area_sizes?: string[]; // from plant_area_sizes table
  challenges?: string[]; // from plant_challenges table
  tech_preferences?: string[]; // from plant_tech_preferences table
  care_notes?: string[]; // from plant_care_notes table

  locations?: ILocation[]; // from plant_locations table
}
